services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
    - "./redis_data:/data"

